import { logger } from '../utils/logger';

export interface ExportOptions {
  minify?: boolean;
  includeMetadata?: boolean;
  includeComments?: boolean;
  format?: string;
  template?: string;
  variables?: Record<string, any>;
  customSettings?: Record<string, any>;
}

export interface GenerationResult {
  content: string;
  filename: string;
  mimeType: string;
  fileExtension: string;
  encoding: string;
  size: number;
  metadata: Record<string, any>;
}

export abstract class BaseGenerator {
  protected formatType: string;
  protected defaultMimeType: string;
  protected defaultExtension: string;

  constructor(formatType: string, mimeType: string, extension: string) {
    this.formatType = formatType;
    this.defaultMimeType = mimeType;
    this.defaultExtension = extension;
  }

  async generate(
    data: any,
    options: ExportOptions = {}
  ): Promise<GenerationResult> {
    try {
      const startTime = Date.now();
      
      // Validate input data
      this.validateInput(data);
      
      // Pre-process data if needed
      const processedData = await this.preProcess(data, options);
      
      // Generate the content
      const content = await this.generateContent(processedData, options);
      
      // Post-process the content
      const finalContent = await this.postProcess(content, options);
      
      // Generate filename
      const filename = this.generateFilename(data, options);
      
      // Calculate metadata
      const metadata = {
        generatedAt: new Date().toISOString(),
        generator: this.formatType,
        generationTimeMs: Date.now() - startTime,
        dataSize: JSON.stringify(data).length,
        options: options
      };
      
      const result: GenerationResult = {
        content: finalContent,
        filename,
        mimeType: this.getMimeType(options),
        fileExtension: this.getFileExtension(options),
        encoding: 'UTF-8',
        size: Buffer.byteLength(finalContent, 'utf8'),
        metadata
      };
      
      logger.debug('Export generation completed', {
        formatType: this.formatType,
        filename: result.filename,
        size: result.size,
        generationTime: metadata.generationTimeMs
      });
      
      return result;
    } catch (error) {
      logger.error('Export generation failed', {
        formatType: this.formatType,
        error: error.message,
        options
      });
      throw error;
    }
  }

  // Abstract methods that must be implemented by subclasses
  protected abstract generateContent(data: any, options: ExportOptions): Promise<string>;
  
  // Optional override methods
  protected validateInput(data: any): void {
    if (!data) {
      throw new Error('Input data is required');
    }
  }
  
  protected async preProcess(data: any, options: ExportOptions): Promise<any> {
    return data;
  }
  
  protected async postProcess(content: string, options: ExportOptions): Promise<string> {
    if (options.minify && this.canMinify()) {
      return this.minifyContent(content);
    }
    return content;
  }
  
  protected generateFilename(data: any, options: ExportOptions): string {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const baseName = data.name || data.title || 'export';
    const sanitizedName = baseName.replace(/[^a-zA-Z0-9-_]/g, '_');
    return `${sanitizedName}_${timestamp}${this.getFileExtension(options)}`;\n  }
  
  protected getMimeType(options: ExportOptions): string {
    return options.customSettings?.mimeType || this.defaultMimeType;
  }
  
  protected getFileExtension(options: ExportOptions): string {
    return options.customSettings?.fileExtension || this.defaultExtension;
  }
  
  protected canMinify(): boolean {
    return false; // Override in subclasses that support minification
  }
  
  protected minifyContent(content: string): string {
    // Basic minification - remove extra whitespace
    return content.replace(/\s+/g, ' ').trim();
  }
  
  protected formatJSON(obj: any, options: ExportOptions): string {
    if (options.minify) {
      return JSON.stringify(obj);
    }
    return JSON.stringify(obj, null, 2);
  }
  
  protected addMetadataHeader(content: string, data: any, options: ExportOptions): string {
    if (!options.includeMetadata) {
      return content;
    }
    
    const metadata = {
      generatedAt: new Date().toISOString(),
      generator: `Imagineer Export Engine - ${this.formatType}`,
      source: data.source || 'Unknown',
      version: '1.0.0'
    };
    
    const header = this.formatMetadataHeader(metadata);
    return header + content;
  }
  
  protected formatMetadataHeader(metadata: Record<string, any>): string {
    return `<!-- Generated by ${metadata.generator} at ${metadata.generatedAt} -->\n\n`;
  }
  
  protected escapeHtml(text: string): string {
    const map: Record<string, string> = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#39;'
    };
    return text.replace(/[&<>"']/g, (m) => map[m]);
  }
  
  protected sanitizeFilename(filename: string): string {
    return filename
      .replace(/[^a-zA-Z0-9-_.]/g, '_')
      .replace(/_{2,}/g, '_')
      .replace(/^_|_$/g, '');
  }
}